# Generated by Django 3.2.5 on 2021-07-19 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirmName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Firm name',
                'verbose_name_plural': 'Firm names',
            },
        ),
        migrations.CreateModel(
            name='FirmInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('date', models.DateField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_2_web.firmname', verbose_name='Firm name')),
            ],
            options={
                'verbose_name': 'Firm info',
                'verbose_name_plural': 'Firms info',
            },
        ),
    ]
